import json

def generate_final_database():
    # --- MIỀN BẮC (50 MÓN) ---
    north = [
        ("Phở Bò Hà Nội", ["bánh phở", "thịt bò", "quế", "hồi", "thảo quả", "gừng", "hành lá"], ["Ninh xương bò cùng gừng nướng 8 tiếng để lấy nước dùng trong.", "Thịt bò thái mỏng chần sơ qua nước dùng nóng.", "Xếp bánh phở ra tô, thêm thịt và hành lá rồi chan nước dùng."], 450),
        ("Bún Chả Hà Nội", ["thịt ba chỉ", "bún", "đu đủ", "nước mắm", "hành tím", "tỏi"], ["Thịt ba chỉ thái mỏng nướng than hoa cho cháy cạnh.", "Làm nước chấm chua ngọt với đu đủ và su hào thái lát.", "Dùng bún chấm bát nước mắm kèm thịt nướng và rau sống."], 600),
        ("Bún Đậu Mắm Tôm", ["bún lá", "đậu phụ", "mắm tôm", "thịt heo", "tía tô", "chanh"], ["Đậu phụ cắt miếng vuông rồi rán ngập dầu vàng giòn.", "Thịt chân giò luộc chín thái lát mỏng vừa ăn.", "Pha mắm tôm sủi bọt với chanh, đường và ớt tươi."], 552),
        ("Chả Cá Lã Vọng", ["cá lăng", "nghệ", "thì là", "mắm tôm", "đậu phộng", "mẻ"], ["Cá lăng thái miếng ướp nghệ mẻ rồi nướng sơ.", "Xào cá trên chảo với hành hoa và thì là cắt khúc.", "Ăn kèm bún, đậu phộng rang và mắm tôm sủi bọt."], 503),
        ("Nem Rán Hà Nội", ["thịt heo", "miến", "mộc nhĩ", "nấm hương", "bánh đa nem", "trứng"], ["Băm nhỏ thịt và rau củ trộn đều với trứng làm nhân.", "Cuốn nhân vào bánh đa nem thành những cuốn đều nhau.", "Rán nem qua hai lần lửa để vỏ đạt độ giòn rụm."], 404),
        ("Xôi Xéo Hà Nội", ["gạo nếp", "đỗ xanh", "hành phi", "nghệ", "mỡ lợn"], ["Gạo nếp ngâm nghệ đồ chín thành xôi vàng dẻo.", "Đỗ xanh hấp nhừ giã nhuyễn rồi nắm thành viên tròn.", "Cắt đỗ xanh lên xôi, rưới mỡ lợn và hành phi giòn."], 525),
        ("Canh Sấu Sườn Non", ["sườn non", "quả sấu", "hành lá", "ngò gai"], ["Sườn non hầm mềm để lấy nước dùng ngọt thanh.", "Cho sấu tươi vào đun sôi rồi dầm nát tạo vị chua.", "Thêm hành lá ngò gai rồi dùng nóng với cơm trắng."], 306),
        ("Bún Thang", ["bún", "thịt gà", "trứng", "giò lụa", "tôm khô", "nấm hương"], ["Ninh nước dùng xương gà và tôm khô cho vị thanh.", "Thịt gà, giò lụa, trứng tráng đều thái sợi chỉ mỏng.", "Xếp nguyên liệu lên bún theo vòng tròn rồi chan nước dùng."], 387),
        ("Cá Kho Làng Vũ Đại", ["cá trắm", "riềng", "tương bần", "nước màu", "chanh"], ["Ướp cá trắm với tương bần và riềng gừng giã nhỏ.", "Xếp riềng đáy nồi đất, đặt cá lên trên kho lửa nhỏ.", "Kho liên tục 12 tiếng cho xương nhừ thịt cá săn chắc."], 458),
        ("Bún Ốc Hà Nội", ["bún", "ốc nhồi", "cà chua", "giấm bỗng", "tía tô"], ["Ốc luộc chín khêu thịt rồi xào sơ với nghệ.", "Nấu nước dùng cà chua kết hợp với giấm bỗng chua thanh.", "Cho bún vào tô thêm ốc và chan nước dùng thật nóng."], 359),
        ("Miến Lươn", ["miến dong", "lươn", "giá đỗ", "rau răm", "gừng"], ["Sơ chế lươn sạch nhớt rồi chiên giòn hoặc xào săn.", "Ninh xương lươn lấy nước dùng thanh ngọt.", "Chần miến cho vào bát thêm lươn và rau răm."], 320),
        ("Bún Mọc", ["bún", "giò sống", "mộc nhĩ", "sườn non", "hành lá"], ["Nặn viên mọc từ giò sống và mộc nhĩ băm nhỏ.", "Ninh sườn non lấy nước dùng trong và ngọt.", "Thả viên mọc vào đun chín rồi chan vào tô bún."], 410),
        ("Bún Cá Cay Hải Phòng", ["bún", "cá thu", "ớt tươi", "dọc mùng", "nghệ"], ["Cá chiên vàng giòn rụm trong chảo dầu nóng.", "Nấu nước lèo chua cay cùng nghệ và ớt màu.", "Ăn kèm bún sợi nhỏ và dọc mùng chần sơ."], 390),
        ("Thịt Đông", ["thịt chân giò", "mộc nhĩ", "bì heo", "tiêu hạt"], ["Ninh nhừ thịt chân giò và bì heo với mộc nhĩ.", "Nêm nhiều tiêu hạt tạo vị cay ấm đặc trưng.", "Đổ ra bát để ngăn mát tủ lạnh cho đông lại."], 450),
        ("Bánh Cuốn Thanh Trì", ["bột gạo", "hành phi", "nước mắm", "chả quế"], ["Tráng lớp bột gạo mỏng trên vải hấp chín hơi nước.", "Thoa mỡ hành lên mặt bánh rắc hành phi thơm.", "Chấm mắm chua ngọt và ăn kèm miếng chả quế."], 320),
        ("Chả Lá Lốt", ["thịt heo băm", "lá lốt", "hành khô", "tiêu"], ["Trộn thịt băm với hành tím và tiêu cho dậy mùi.", "Cuốn thịt vào lá lốt thành dạng ống chặt tay.", "Rán vàng đều các mặt trên chảo lửa vừa."], 360),
        ("Canh Cua Rau Muống", ["cua đồng", "rau muống", "khoai sọ", "mắm tôm"], ["Giã cua lọc lấy nước đun sôi cho nổi riêu thịt.", "Cho khoai sọ ninh mềm rồi thả rau muống vào.", "Nêm chút mắm tôm cho bát canh đậm đà chuẩn vị."], 200),
        ("Gà Tần Thuốc Bắc", ["thịt gà", "thuốc bắc", "ngải cứu", "gừng"], ["Cho gà vào thố cùng các vị thuốc bắc thảo mộc.", "Xếp lá ngải cứu xung quanh gà để tạo mùi thơm.", "Hấp cách thủy trong 2 tiếng cho gà chín mềm rục."], 480),
        ("Nộm Đu Đủ Bò Khô", ["thịt bò khô", "đu đủ xanh", "đậu phộng", "kinh giới"], ["Đu đủ bào sợi bóp muối vắt kiệt nước cho giòn.", "Trộn đu đủ với nước mắm chua ngọt và bò khô xé.", "Rắc thêm lạc rang và rau kinh giới lên mặt."], 250),
        ("Xôi Gấc", ["gạo nếp", "quả gấc", "rượu trắng", "đường"], ["Trộn gấc với gạo nếp thêm chút rượu trắng lấy màu.", "Đồ xôi chín dẻo thơm rồi trộn thêm chút đường.", "Nén xôi vào khuôn cho đẹp mắt để thắp hương."], 500),
        ("Bún Riêu Cua Hà Nội", ["bún", "cua đồng", "đậu phụ", "cà chua", "mẻ"], ["Làm riêu cua từ cua đồng tươi đun nhỏ lửa.", "Rán đậu phụ vàng chần rau muống ăn kèm.", "Chan nước dùng riêu chua thanh từ mẻ vào tô."], 430),
        ("Cá Chép Om Dưa", ["cá chép", "dưa chua", "thịt ba chỉ", "hành lá"], ["Rán sơ cá chép cho săn chắc thịt.", "Xào ba chỉ với dưa chua cho thấm vị chua mặn.", "Cho cá vào om cùng dưa trong 30 phút lửa nhỏ."], 420),
        ("Nem Nắm Nam Định", ["thịt heo", "thính gạo", "lá sung", "tỏi"], ["Luộc thịt heo thái nhỏ trộn cùng thính gạo thơm.", "Nắm thành từng viên tròn chặt tay bọc lá sung.", "Chấm nước mắm tỏi ớt cay nồng đậm vị quê."], 350),
        ("Miến Trộn Gà", ["miến", "thịt gà", "giá đỗ", "đậu phộng", "xì dầu"], ["Chần miến dai vừa tới trộn cùng dầu hào xì dầu.", "Thêm gà xé giá đỗ và đậu phộng rang giòn.", "Trộn đều các nguyên liệu cho thấm sốt đậm đà."], 340),
        ("Chả Rươi Hà Nội", ["con rươi", "trứng gà", "vỏ quýt", "thịt băm"], ["Đánh tan rươi cùng thịt băm và vỏ quýt thái chỉ.", "Trộn thêm trứng gà nêm gia vị vừa miệng.", "Rán vàng giòn trên chảo tỏa mùi thơm đặc trưng."], 420),
        ("Canh Rau Ngót Thịt Băm", ["rau ngót", "thịt heo băm", "hành tím"], ["Xào săn thịt băm với hành tím thơm phức.", "Vò nát rau ngót thả vào nước sôi cùng thịt xào.", "Nấu sôi lại 2 phút rồi dùng nóng với cơm."], 150),
        ("Bún Dọc Mùng", ["bún", "dọc mùng", "mọc", "chân giò", "nghệ"], ["Làm sạch dọc mùng bóp muối nghệ cho vàng.", "Ninh chân giò lấy nước lèo trong thanh ngọt.", "Xếp mọc và dọc mùng lên bún rồi chan nước."], 400),
        ("Bánh Tôm Hồ Tây", ["khoai lang", "tôm tươi", "bột mì", "bột năng"], ["Thái sợi khoai lang trộn cùng hỗn hợp bột.", "Đặt tôm lên miếng khoai rồi chiên ngập dầu.", "Ăn kèm nước mắm đu đủ và rau sống giòn."], 450),
        ("Nem Chua Rán", ["nem chua", "bột chiên xù", "ớt tương"], ["Lăn nem chua qua lớp bột chiên xù mỏng.", "Chiên ngập dầu lửa lớn cho vỏ ngoài giòn rụm.", "Chấm cùng tương ớt cay nồng lúc còn nóng."], 380),
        ("Gà Rang Muối", ["thịt gà", "gạo nếp", "đỗ xanh", "sả", "lá chanh"], ["Làm muối gạo từ nếp và đỗ xanh rang xay.", "Chiên gà vàng giòn rồi xóc cùng muối sả phi.", "Rắc thêm lá chanh thái chỉ cho dậy mùi thơm."], 520),
        ("Phở Cuốn Hà Nội", ["bánh phở miếng", "thịt bò", "rau thơm", "xà lách"], ["Xào thịt bò với tỏi cho săn và đậm đà.", "Trải miếng bánh phở cuốn thịt bò cùng rau sống.", "Chấm nước mắm tỏi ớt chua ngọt đặc trưng."], 300),
        ("Canh Măng Khô", ["măng khô", "móng giò", "hành lá"], ["Măng khô ngâm nở xé sợi hầm cùng móng giò.", "Ninh lâu cho măng mềm quyện vị béo của móng.", "Nêm gia vị và rắc hành lá cắt khúc dài."], 450),
        ("Rau Muống Xào Tỏi", ["rau muống", "tỏi", "dầu ăn"], ["Chần rau muống giữ màu xanh rồi vớt ra nước lạnh.", "Phi thơm thật nhiều tỏi băm với dầu ăn.", "Xào rau nhanh tay trên lửa cực lớn."], 120),
        ("Cá Diếc Kho Tương", ["cá diếc", "tương bần", "gừng"], ["Sơ chế cá diếc sạch kho cùng tương bần và gừng.", "Đun lửa nhỏ liu riu cho nước tương thấm vào cá.", "Kho đến khi nước cạn cá chắc thịt thơm mùi tương."], 350),
        ("Bún Cá Hải Phòng", ["bún", "cá đồng", "thì là", "nghệ"], ["Rán cá đồng giòn tan trong chảo dầu.", "Nấu nước dùng nghệ nêm giấm bỗng chua dịu.", "Trình bày thì là cá rán lên bún và chan nước."], 370),
        ("Chả Quế", ["thịt lợn", "bột quế", "mật ong"], ["Xay nhuyễn thịt lợn trộn cùng bột quế thơm.", "Phết thịt lên khuôn nướng vàng hai mặt.", "Thoa chút mật ong cho màu sắc thêm bắt mắt."], 400),
        ("Nem Tai", ["tai heo", "thính gạo", "lá sung", "ớt"], ["Luộc tai heo giòn rồi thái sợi thật mỏng.", "Trộn tai heo với thính gạo và tỏi băm.", "Cuốn lá sung chấm nước mắm mặn ớt tỏi."], 280),
        ("Phở Trộn", ["bánh phở", "thịt gà", "xì dầu", "hành khô"], ["Chần bánh phở tơi xốp cho vào tô lớn.", "Thêm thịt gà xé và hành khô phi thơm.", "Rưới nước sốt xì dầu đặc chế rồi trộn đều."], 360),
        ("Cháo Sườn Hà Nội", ["gạo tẻ", "sườn non", "quẩy"], ["Ninh gạo với sườn non cho cháo nhừ mịn.", "Xé nhỏ thịt sườn trộn đều vào nồi cháo.", "Ăn kèm quẩy giòn và chút hạt tiêu xay."], 320),
        ("Bánh Đa Cua", ["bánh đa đỏ", "cua đồng", "chả lá lốt", "rau muống"], ["Nấu nước riêu cua đồng gạch xào hành phi.", "Chần bánh đa đỏ Hải Phòng cho vào bát.", "Thêm chả lá lốt rau muống chan nước dùng."], 430),
        ("Canh Sườn Nấu Me", ["sườn non", "me", "cà chua", "hành lá"], ["Hầm sườn non cho mềm rồi cho nước me vào.", "Thêm cà chua bổ múi cau đun sôi nêm gia vị.", "Rắc hành lá dùng nóng cùng cơm trắng."], 310),
        ("Gà Rang Gừng", ["thịt gà", "gừng tươi", "lá chanh"], ["Chặt gà miếng vừa ăn rang sém cạnh với gừng.", "Nêm nước mắm đường cho gà có màu vàng nâu.", "Rắc lá chanh thái sợi khi vừa tắt bếp."], 400),
        ("Cá Rô Phi Rán Giòn", ["cá rô phi", "bột chiên", "nước mắm gừng"], ["Tẩm cá qua lớp bột chiên mỏng rồi rán giòn.", "Chiên cá lửa vừa cho chín đều bên trong.", "Chấm cùng nước mắm gừng cay nồng đậm vị."], 450),
        ("Đậu Phụ Sốt Cà Chua", ["đậu phụ", "cà chua", "hành lá"], ["Rán vàng đậu phụ cắt miếng vuông nhỏ.", "Xào cà chua thành sốt rồi cho đậu vào đun.", "Nêm gia vị rắc hành lá dùng cùng cơm nóng."], 280),
        ("Bún Mọc Sườn", ["bún", "giò sống", "sườn", "măng chua"], ["Vò viên giò sống làm mọc ninh cùng sườn.", "Thêm măng chua vào nước dùng lấy vị thanh.", "Chan nước dùng vào tô bún mọc sườn non."], 420),
        ("Ba Chỉ Luộc Chấm Mắm Tôm", ["thịt ba chỉ", "hành tím", "nước mắm"], ["Luộc thịt với hành tím cho thơm và trắng thịt.", "Thái lát thịt thật mỏng bày ra đĩa.", "Chấm cùng mắm tôm pha chanh đường ớt."], 400),
        ("Canh Bí Nấu Tôm", ["bí xanh", "tôm tươi", "hành tím"], ["Giã tôm tươi xào thơm với hành tím băm.", "Cho bí xanh vào nấu cùng nước dùng ngọt.", "Nêm nếm gia vị dùng làm món canh mát."], 180),
        ("Lòng Lợn Luộc", ["lòng lợn", "tiết", "rau húng"], ["Làm sạch lòng heo luộc cùng gừng sả.", "Thái miếng vừa ăn trình bày ra đĩa.", "Chấm mắm tôm ăn kèm rau húng chó."], 500),
        ("Su Su Xào Tỏi", ["ngọn su su", "tỏi", "dầu ăn"], ["Nhặt ngọn su su non xào nhanh với tỏi phi.", "Giữ độ xanh và giòn cho ngọn su su.", "Dùng làm món rau xào trong bữa cơm."], 110),
        ("Cá Trắm Kho Riềng", ["cá trắm", "riềng", "nước chè xanh"], ["Ướp cá với riềng giã nhỏ và nước mắm.", "Kho cá với nước chè xanh cho chắc thịt.", "Đun cạn nước cho cá có màu cánh gián."], 430)
    ]

    # --- MIỀN TRUNG (50 MÓN) ---
    central = [
        ("Bún Bò Huế", ["bún sợi to", "thịt bò", "giò heo", "mắm ruốc", "sả", "ớt bột"], ["Ninh xương bò và giò heo với sả và mắm ruốc Huế.", "Thịt bò thái mỏng chần tái, giò heo chặt miếng.", "Chan nước dùng cay nồng mùi sả vào tô bún sợi lớn."], 600),
        ("Mì Quảng Tôm Thịt", ["mì quảng", "tôm", "thịt heo", "bánh tráng", "hạt nén", "đậu phộng"], ["Nấu nước lèo đậm đặc từ tôm và thịt heo băm.", "Phi thơm hạt nén với dầu phộng lấy mùi thơm đặc trưng.", "Trình bày mì với ít nước dùng, bánh tráng và lạc."], 501),
        ("Cơm Hến Huế", ["cơm", "hến", "da heo", "mắm ruốc", "rau dọc mùng", "ớt xiêm"], ["Hến luộc lấy nước và thịt, xào hến đậm đà gia vị.", "Pha nước luộc hến nóng với gừng và mắm ruốc.", "Trộn cơm nguội với hến, rau sống, da heo và ớt."], 422),
        ("Bánh Xèo Miền Trung", ["bột gạo", "tôm", "thịt", "giá đỗ", "ớt bột"], ["Đổ bột gạo mỏng vào chảo nhỏ chiên vàng giòn.", "Thêm nhân tôm thịt giá đỗ vào giữa bánh.", "Cuốn bánh với bánh tráng rau sống chấm mắm nêm."], 453),
        ("Nem Lụi Huế", ["thịt heo", "sả cây", "gia vị", "ớt", "đậu phộng"], ["Quết thịt heo nhuyễn quấn quanh cây sả nướng than.", "Làm nước lèo chấm từ gan heo và lạc xay béo.", "Dùng nem cuốn bánh tráng chấm nước sốt đặc biệt."], 484),
        ("Bánh Bèo Huế", ["bột gạo", "tôm khô", "hành lá", "da heo chiên"], ["Hấp bột gạo trong chén nhỏ chín trắng đục.", "Làm tôm chấy xào khô rắc lên mặt bánh.", "Rưới mỡ hành và da heo chiên giòn lên chén bánh."], 320),
        ("Bún Cá Ngừ Đại Dương", ["bún", "cá ngừ", "thơm", "cà chua", "ớt xanh"], ["Cá ngừ kho sơ với thơm cà chua cho thấm vị.", "Nấu nước lèo chua cay kiểu miền Trung đặc trưng.", "Xếp cá ngừ lên bún rồi chan nước lèo nóng."], 350),
        ("Cao Lầu Hội An", ["mì cao lầu", "thịt xá xíu", "giá đỗ", "rau thơm"], ["Ram thịt heo ngũ vị hương làm xá xíu thái mỏng.", "Trụng mì cao lầu và giá đỗ qua nước sôi.", "Xếp thịt lên mì rưới sốt ram và thêm rau sống."], 457),
        ("Hến Xúc Bánh Tráng", ["hến", "bánh tráng", "sả", "ớt", "rau răm"], ["Hến xào nhanh với sả băm ớt tươi và hành tím.", "Thêm rau răm thái nhỏ vào chảo hến trước khi tắt bếp.", "Bẻ bánh tráng nướng xúc hến xào dùng làm món ăn chơi."], 388),
        ("Bún Mắm Nêm Đà Nẵng", ["bún", "thịt heo", "mắm nêm", "thơm", "rau sống"], ["Thịt heo luộc chín thái miếng mỏng vừa ăn.", "Pha mắm nêm với thơm băm nhỏ và tỏi ớt.", "Xếp bún thịt rau vào tô rưới mắm nêm lên."], 409),
        ("Chả Ram Ít", ["tôm", "thịt", "bánh tráng mỏng", "bánh ít"], ["Cuốn tôm thịt làm ram rồi chiên vàng giòn.", "Hấp bánh ít bột gạo cho dẻo dai trắng trong.", "Đặt ram lên bánh ít chấm cùng nước mắm chua."], 460),
        ("Bánh Lọc Trần", ["bột năng", "tôm", "thịt ba chỉ", "hành lá"], ["Nhào bột năng nước sôi gói nhân tôm thịt.", "Luộc bánh trong nước sôi cho đến khi bánh trong.", "Vớt bánh ra trộn mỡ hành cho bóng miếng bánh."], 340),
        ("Bánh Nậm", ["bột gạo", "tôm", "lá dong"], ["Trải bột gạo lá dong rắc tôm khô giã nhuyễn.", "Gói mỏng rồi hấp chín trong 15 phút lửa lớn.", "Dùng nóng chấm với nước mắm mặn có ớt."], 310),
        ("Bún Sứa Quy Nhơn", ["bún", "sứa tươi", "chả cá", "đậu phộng"], ["Sứa tươi ngâm nước muối gừng thái miếng vừa.", "Nấu nước lèo cá thu thanh ngọt chan vào bún.", "Xếp chả cá chiên và sứa lên mặt tô bún."], 320),
        ("Cá Nục Hấp Cuốn Bánh Tráng", ["cá nục", "bánh tráng", "rau muống", "ớt xanh"], ["Hấp cá nục với hành gừng cho thơm và chắc thịt.", "Cuốn cá hấp rau muống vào bánh tráng Đại Lộc.", "Chấm mắm nêm pha thơm cay nồng kiểu miền Trung."], 380),
        ("Tré Bình Định", ["tai heo", "thịt đầu", "riềng", "thính", "lá ổi"], ["Thái thịt tai luộc chín trộn riềng thính thơm.", "Gói chặt trong lá ổi và lá chuối để 2 ngày.", "Khi ăn xé nhỏ trộn cùng rau thơm và tỏi."], 300),
        ("Gà Chỉ Phú Yên", ["thịt gà", "lá giang", "ớt xiêm"], ["Hấp hoặc nướng gà xé chấm muối tiêu ớt xiêm.", "Lấy nước gà nấu lá giang tạo vị chua thanh.", "Dùng kèm cơm lam nướng vàng giòn rụm."], 450),
        ("Lòng Xào Nghệ", ["lòng lợn", "nghệ tươi", "hẹ"], ["Làm sạch lòng heo thái miếng xào nghệ tươi giã.", "Thêm hẹ đảo nhanh tay cho dậy mùi thơm nồng.", "Món ăn trị ho dân gian đặc sản miền Trung."], 380),
        ("Bánh Căn Phan Thiết", ["bột gạo", "trứng cút", "mỡ hành", "mắm kho"], ["Đổ bột vào khuôn đất nung nóng thêm trứng cút.", "Nướng bánh giòn đáy mặt trên dẻo thơm mỡ hành.", "Chấm nước mắm cá kho đậm đà chuẩn vị."], 422),
        ("Bún Song Thằn", ["đậu xanh", "thịt gà", "nấm"], ["Sử dụng sợi bún làm thủ công từ đậu xanh.", "Nấu nước lèo gà thanh mát thêm gà xé nấm.", "Dùng nóng trong các dịp lễ hội truyền thống."], 350),
        ("Ram Tôm Đất", ["tôm đất", "bánh tráng", "hành tím"], ["Cuốn tôm đất nguyên con chiên vàng rụm.", "Vỏ bánh giòn tan thịt tôm ngọt lịm bên trong.", "Ăn kèm rau sống và nước mắm mặn Bình Định."], 440),
        ("Canh Chua Cá Khoai", ["cá Khoai", "me", "rau cần"], ["Nấu nước me chua thả cá khoai chín nhanh.", "Cá chín tới cho rau cần hành lá vào bát.", "Dùng ngay lúc nóng để giữ độ ngọt của cá."], 220),
        ("Cá Ngừ Kho Thơm", ["cá ngừ", "thơm", "ớt khô"], ["Chiên sơ cá ngừ kho với thơm đậm đà.", "Đun lửa nhỏ cho nước màu dừa thấm vào cá.", "Vị cá bùi béo quyện cùng vị thơm chua ngọt."], 400),
        ("Cơm Gà Tam Kỳ", ["gạo tẻ", "gà ta", "nghệ", "rau răm"], ["Nấu cơm nghệ bằng nước luộc gà béo ngậy.", "Xé gà trộn rau răm hành tây chanh đường.", "Trình bày cơm kèm gà bóp chuẩn vị Quảng."], 550),
        ("Bánh Vá", ["bột gạo", "tôm", "giá", "đậu xanh"], ["Đổ bột vào vá sâu thêm tôm giá chiên ngập dầu.", "Bánh giòn khú chấm nước mắm tỏi ớt cay.", "Món ăn dân dã đặc sản vùng Gò Công."], 480),
        ("Lẩu Thả Phan Thiết", ["cá mai", "thịt heo", "trứng", "bún"], ["Sơ chế cá mai bóp chanh gừng lóc xương.", "Bày các loại nhân trong vỏ hoa chuối đẹp mắt.", "Chan nước dùng tôm thịt nóng hổi béo thơm."], 500),
        ("Gỏi Cá Nam Ô", ["cá trích", "thính", "gừng", "riềng"], ["Thái mỏng cá trích trộn riềng thính đặc chế.", "Cuốn lá rừng với cá và rau sống đa dạng.", "Chấm nước sốt cá sệt cay nồng Đà Nẵng."], 320),
        ("Bún Cá Thu", ["bún", "cá thu", "cà chua", "hành lá"], ["Ninh xương cá lấy nước dùng thêm cà chua thơm.", "Cá thu cắt lát kho đậm vị xếp lên bún.", "Chan nước dùng nóng nêm hành thì là miền Trung."], 380),
        ("Bánh Canh Cá Lóc", ["bột gạo", "cá lóc", "hành lá"], ["Nấu sợi bánh canh thủ công từ bột gạo.", "Dằm cá lóc kho đậm đà thêm nhiều hành tăm.", "Chan nước dùng cay nồng mùi tiêu rừng."], 390),
        ("Cháo Lươn Nghệ An", ["gạo", "lươn", "nghệ", "hành tăm"], ["Xào thịt lươn nghệ hành tăm cho dậy mùi.", "Nấu cháo gạo tẻ nhừ mịn mượt như súp.", "Trộn lươn vào cháo rắc rau răm ăn nóng."], 360),
        ("Mực Rim Me", ["mực khô", "me", "ớt", "đường"], ["Rim mực khô với sốt me chua cay mặn ngọt.", "Đun lửa nhỏ đến khi sốt me keo bám mực.", "Dùng làm món nhâm nhi hoặc ăn với cơm."], 400),
        ("Ram Bánh Mướt", ["bột gạo", "giò sống", "hành phi"], ["Tráng bánh mướt mỏng dẻo cuốn nhân giò sống.", "Chiên vàng ram bánh mướt giòn rụm thơm tỏi.", "Chấm nước mắm chua cay đặc trưng Nghệ Tĩnh."], 420),
        ("Bún Thịt Nướng Huế", ["bún", "thịt heo", "vừng", "tương đậu"], ["Nướng thịt heo sả vừng trên than hồng vàng rực.", "Làm sốt chấm từ tương đậu nành xay nhuyễn.", "Trộn bún rau sống rưới sốt béo ngậy lên."], 510),
        ("Bánh Thuẫn", ["trứng", "bột năng", "đường"], ["Đánh trứng với bột năng nướng khuôn gang than.", "Bánh nở bung như hoa mai vàng đẹp mắt.", "Dùng làm quà bánh truyền thống dịp lễ tết."], 250),
        ("Nem Chua Ninh Hòa", ["thịt heo", "da heo", "tỏi", "ớt"], ["Quết thịt heo thật nhuyễn trộn bì heo sợi.", "Gói lá chùm ruột để lên men chua tự nhiên.", "Ăn kèm tỏi sống và nước chấm tương cay."], 290),
        ("Bún Cá Cam", ["bún", "cá cam", "thơm", "cà chua"], ["Kho cá cam đậm đà nêm gia vị miền Trung.", "Nấu nước lèo thơm cà chua chan vào bún.", "Vị cá cam béo bùi ăn cùng bún tươi."], 380),
        ("Chè Cung Đình Huế", ["hạt sen", "đậu xanh", "đường phèn"], ["Nấu nhừ hạt sen tươi và đậu xanh bỏ vỏ.", "Thêm đường phèn vị ngọt thanh mát lạnh.", "Món tráng miệng thanh tao chuẩn vị cố đô."], 200),
        ("Canh Hến Nấu Bầu", ["hến", "bí bầu", "hành lá"], ["Luộc hến lấy nước nấu hến xào sả ớt.", "Cho bầu băm sợi vào nồi nước hến đun sôi.", "Nêm hành lá rau răm dùng mát ngày hè."], 180),
        ("Bánh Bèo Chén", ["bột gạo", "tôm chấy", "mỡ hành"], ["Hấp bánh gạo trong chén sứ nhỏ vừa ăn.", "Rắc tôm chấy cháy cạnh và mỡ hành thơm.", "Rưới nước mắm ngọt cay vào chén bánh."], 300),
        ("Cá Cam Kho Ớt Xanh", ["cá cam", "ớt xanh", "nước mắm"], ["Chiên sơ cá cam kho cùng thật nhiều ớt xanh.", "Đun cạn nước mắm cho vị cay thấm vào thịt.", "Món ăn hao cơm đặc trưng người miền Trung."], 410),
        ("Gà Kho Sả Nghệ", ["thịt gà", "sả", "nghệ", "ớt"], ["Ướp gà với nghệ sả giã nhỏ nêm đậm đà.", "Kho gà săn thịt lửa nhỏ cho thấm gia vị.", "Dùng nóng cùng cơm gạo mới rất ấm bụng."], 430),
        ("Lươn Xào Sả Ớt", ["lươn", "sả", "ớt", "đậu phộng"], ["Làm sạch lươn xào nhanh với sả ớt băm.", "Thêm đậu phộng rang giòn thơm sần sật.", "Ăn kèm bánh tráng nướng giòn rụm miền Trung."], 390),
        ("Bún Chả Cá Quy Nhơn", ["bún", "chả cá", "thì là", "măng"], ["Làm chả cá thu dai giòn thơm thì là.", "Nấu nước lèo xương cá nêm măng chua thanh.", "Thêm chả cá chan nước dùng bốc khói."], 400),
        ("Gỏi Sứa Xoài Xanh", ["sứa", "xoài xanh", "đậu phộng"], ["Sơ chế sứa giòn trộn xoài bào sợi chua.", "Rưới mắm chua ngọt rắc lạc rang vàng.", "Ăn kèm bánh phồng tôm giòn tan mát mẻ."], 180),
        ("Bánh Hỏi Cháo Lòng", ["bánh hỏi", "cháo", "lòng lợn"], ["Nấu cháo huyết loãng nhừ thơm tiêu gừng.", "Làm bánh hỏi rưới mỡ hành lá hẹ tươi.", "Ăn lòng luộc kèm bánh hỏi cháo nóng."], 550),
        ("Cá Tai Tượng Chiên", ["cá tai tượng", "mắm nêm", "rau"], ["Chiên cá ngập dầu cho vảy dựng xù giòn.", "Cuốn bánh tráng với rau sống rừng đa dạng.", "Chấm mắm nêm đậm đà mang phong vị biển."], 480),
        ("Mực Hấp Gừng", ["mực tươi", "gừng", "hành lá"], ["Hấp mực tươi với gừng thái chỉ hành lá.", "Mực chín giòn chấm nước mắm gừng cay.", "Dùng nóng giữ trọn độ ngọt của hải sản."], 250),
        ("Súp Lươn Nghệ An", ["lươn", "nghệ", "hành tăm", "ớt"], ["Nấu súp lươn đậm đà nghệ và hành tăm.", "Ăn kèm bánh mì hoặc bánh mướt chả phượng.", "Vị súp cay nồng đặc trưng xứ Nghệ."], 320),
        ("Bánh Căn Tôm Mực", ["bột gạo", "tôm", "mực", "mỡ hành"], ["Đổ khuôn bánh căn thêm hải sản tươi rói.", "Nướng giòn đáy mềm mặt béo ngậy trứng.", "Chấm nước mắm đậu phộng chua cay bắt miệng."], 440),
        ("Cơm Gà Hội An", ["gạo", "thịt gà", "nghệ", "hành tây"], ["Nấu cơm nghệ bằng nước luộc gà thơm dẻo.", "Xé gà trộn rau răm hành tây muối chanh.", "Trình bày đĩa cơm kèm thịt gà bóp rau."], 540)
    ]

    # --- MIỀN NAM (50 MÓN) ---
    south = [
        ("Canh Chua Cá Lóc", ["cá lóc", "me", "bông súng", "bạc hà", "đường"], ["Nấu nước me chua thả cá lóc chín tới.", "Cho các loại rau sông nước vào đun sôi.", "Nêm đường thốt nốt ngọt thanh chuẩn Nam."], 350),
        ("Cơm Tấm Sườn Bì Chả", ["gạo tấm", "sườn", "bì heo", "chả trứng"], ["Nướng sườn mật ong vàng thơm than hoa.", "Làm chả trứng hấp béo ngậy thịt trứng.", "Rưới mỡ hành lên cơm tấm tơi xốp."], 751),
        ("Lẩu Mắm Miền Tây", ["mắm linh", "mắm sặc", "tôm", "ba rọi"], ["Nấu rã mắm linh sặc lọc nước cốt mắm.", "Ninh sả ớt thêm nước cốt dừa béo thơm.", "Nhúng rau điên điển súng tôm cá vào nồi."], 802),
        ("Bánh Khọt Vũng Tàu", ["bột gạo", "tôm", "nước cốt dừa", "hành"], ["Đổ bột cốt dừa vào khuôn chiên giòn đáy.", "Thêm tôm tươi vào giữa chín mềm mặt trên.", "Cuốn xà lách chấm nước mắm chua ngọt."], 403),
        ("Hủ Tiếu Nam Vang", ["hủ tiếu", "tôm", "gan heo", "trứng cút"], ["Ninh nước xương ống tôm khô mực nướng.", "Chần hủ tiếu dai thêm topping tôm thịt.", "Chan nước dùng nóng bốc khói vào tô."], 504),
        ("Cá Kho Tộ Nam Bộ", ["cá hú", "nước mắm", "đường", "tiêu"], ["Ướp cá hú màu mắm tiêu đường thốt nốt.", "Kho cá trong tộ đất lửa nhỏ sệt nước.", "Rắc hành lá tiêu xanh béo ngậy đậm đà."], 425),
        ("Bánh Xèo Nam Bộ", ["bột gạo", "tôm", "thịt heo", "cốt dừa"], ["Tráng bánh chảo lớn mỏng vàng béo dừa.", "Cho nhân tôm thịt đậu xanh giá đỗ vào.", "Ăn kèm rau rừng miền Tây chấm mắm ngọt."], 556),
        ("Bún Nước Lèo Sóc Trăng", ["bún", "mắm bò hóc", "cá lóc", "tôm"], ["Ninh mắm bò hóc với ngải bún lấy hương.", "Gỡ thịt cá lóc tôm luộc chín xếp lên bún.", "Chan nước mắm thơm nồng chuẩn vị Sóc Trăng."], 380),
        ("Kho Quẹt Nam Bộ", ["thịt ba chỉ", "tôm khô", "nước mắm", "đường"], ["Thắng mỡ ba chỉ làm tóp mỡ giòn thơm.", "Rim tôm khô với mắm đường keo lại sệt.", "Chấm rau củ luộc hoặc ăn cùng cơm cháy."], 458),
        ("Canh Lá Giang Gà", ["thịt gà", "lá giang", "ớt", "hành tím"], ["Xào gà săn rồi đun sôi cho gà mềm.", "Vò nát lá giang thả vào nồi canh chua.", "Nêm gia vị vừa ăn dùng nóng cùng bún."], 329),
        ("Cá Lóc Nướng Trui", ["cá lóc", "rơm", "mỡ hành", "lạc"], ["Xiên cá lóc tre phủ rơm đốt cháy chín.", "Cạo vảy đen phết mỡ hành lạc rang vàng.", "Gỡ thịt cuốn bánh tráng chấm mắm me."], 400),
        ("Gỏi Cuốn Tôm Thịt", ["bánh tráng", "tôm", "thịt heo", "bún"], ["Luộc thịt heo thái mỏng tôm bóc vỏ.", "Cuốn tôm thịt bún rau thơm vào bánh tráng.", "Chấm tương hột xay béo thơm đậu phộng."], 250),
        ("Bò Kho Nam Bộ", ["thịt bò", "cà rốt", "sả", "bánh mì"], ["Hầm bò gân sả cây sốt bò kho thơm lừng.", "Thêm cà rốt quế hồi ninh bò mềm tan.", "Dùng nóng chấm bánh mì hoặc ăn kèm bún."], 580),
        ("Cơm Gà Xối Mỡ", ["gạo", "thịt gà", "mỡ lợn", "xì dầu"], ["Nấu cơm nước dùng gà hạt vàng tơi xốp.", "Chiên gà xối mỡ nóng da giòn rụm đỏ rực.", "Ăn kèm dưa leo nước tương pha ớt cay."], 680),
        ("Bún Thịt Nướng Sài Gòn", ["bún", "thịt heo", "sả", "chả giò"], ["Nướng thịt heo sả vàng thơm rực lửa.", "Xếp bún chả giò nướng vào tô rau sống.", "Rưới mắm chua ngọt mỡ hành đậu phộng."], 550),
        ("Gỏi Ngó Sen Tôm Thịt", ["ngó sen", "tôm", "thịt", "chanh"], ["Bóp ngó sen giòn với chanh đường mắm.", "Trộn tôm thịt luộc rau răm hành phi.", "Ăn kèm bánh phồng tôm chiên giòn tan."], 280),
        ("Cháo Cá Lóc", ["gạo", "cá lóc", "nấm rơm", "rau đắng"], ["Nấu cháo trắng nhừ mịn thả cá lóc nấm.", "Thịt cá ngọt lịm tan trong bát cháo nóng.", "Ăn kèm rau đắng đất vị đắng thanh."], 340),
        ("Bánh Tằm Bì", ["bánh tằm", "bì heo", "nước cốt dừa"], ["Hấp bánh tằm nóng dẻo sợi trắng mượt.", "Trộn bánh với bì heo thính cốt dừa béo.", "Thêm nước mắm ngọt dưa leo rau thơm."], 450),
        ("Bún Cá Châu Đốc", ["bún", "cá lóc", "nghệ", "mắm linh"], ["Nấu nước lèo nghệ vàng mắm linh thơm.", "Dằm thịt cá lóc xào nghệ vàng tươi xếp bún.", "Chan nước lèo ăn kèm rau nhút điên điển."], 370),
        ("Canh Chua Cá Linh", ["cá linh", "điên điển", "me", "ngò"], ["Đun nước me thả cá linh tươi mùa nước nổi.", "Cá chín nhanh thả bông điên điển vào bát.", "Nêm đường phèn chuẩn vị ngọt miền Tây."], 280),
        ("Chuột Đồng Nướng", ["chuột đồng", "ngũ vị", "mật ong"], ["Chuột đồng sạch ướp gia vị nướng lu vàng.", "Da chuột giòn rụm thịt thơm như gà đồng.", "Chấm mắm xoài hoặc muối tiêu chanh ớt."], 420),
        ("Gỏi Ba Khía", ["ba khía", "đu đủ", "chanh", "ớt"], ["Tách ba khía trộn đu đủ bào chanh đường.", "Vị mặn cay nồng khó cưỡng mùi sông nước.", "Món nhậu khoái khẩu đặc sản miền Tây."], 150),
        ("Vịt Nấu Chao", ["thịt vịt", "chao trắng", "khoai môn"], ["Ướp vịt chao hầm mềm với khoai môn chiên.", "Ăn kèm bún tươi rau muống cải xanh.", "Nước dùng béo ngậy mùi chao đặc trưng."], 650),
        ("Lẩu Cá Kèo", ["cá kèo", "lá giang", "rau đắng"], ["Nấu lẩu lá giang chua thả cá kèo sống.", "Nhúng rau đắng dùng nóng kèm bún sợi.", "Vị chua chát đắng hòa quyện độc đáo."], 400),
        ("Hủ Tiếu Mỹ Tho", ["hủ tiếu khô", "thịt băm", "tôm"], ["Chần sợi hủ tiếu Mỹ Tho dai giòn ráo.", "Trộn sốt đặc chế thêm tôm thịt hành phi.", "Dùng kèm bát nước lèo xương ống nóng."], 480),
        ("Cơm Dừa Bến Tre", ["gạo", "nước dừa", "tôm kho"], ["Cho gạo nước dừa vào quả dừa hấp chín.", "Cơm thơm mùi dừa béo bùi vị tự nhiên.", "Ăn kèm tôm rim mặn ngọt đậm đà."], 500),
        ("Gỏi Sầu Đâu", ["lá sầu đâu", "khô cá sặc", "me"], ["Trụng lá sầu đâu bớt đắng trộn khô sặc.", "Chấm mắm me chua ngọt vị đắng thanh.", "Đặc sản vùng biên thùy miền Tây Nam Bộ."], 220),
        ("Cá Lóc Hấp Bầu", ["cá lóc", "quả bầu", "gừng"], ["Đặt cá lóc gừng vào lòng quả bầu hấp chín.", "Thịt cá ngọt quyện cùng vị thanh mát bầu.", "Chấm mắm gừng cay ăn kèm rau sống bún."], 320),
        ("Bún Kèn Kiên Giang", ["bún", "cá thu", "cốt dừa", "nghệ"], ["Xay thịt cá thu nấu sốt nghệ cốt dừa béo.", "Chan sốt lên bún và rau đu đủ bào sợi.", "Món ăn độc đáo vùng biển đảo Rạch Giá."], 450),
        ("Lẩu Cua Đồng", ["cua đồng", "thịt bò", "mồng tơi"], ["Nấu riêu cua đồng thơm lừng gạch cua xào.", "Nhúng bò rau mồng tơi mướp hương bún.", "Vị ngọt riêu cua hòa cùng rau mát lành."], 520),
        ("Gà Đốt Ô Thum", ["thịt gà", "lá chúc", "sả"], ["Ướp gà lá chúc An Giang đốt vàng da giòn.", "Mùi thơm lá chúc đặc trưng không lẫn lộn.", "Chấm muối ớt chúc cay nồng xé lưỡi."], 580),
        ("Bò Tơ Củ Chi", ["thịt bò tơ", "bánh tráng", "mắm nêm"], ["Hấp thịt bò tơ thái mỏng mềm ngọt tự nhiên.", "Cuốn bánh tráng rau rừng chấm mắm nêm thơm.", "Món ăn nức tiếng vùng đất thép thành đồng."], 400),
        ("Phá Lấu Lòng Bò", ["lòng bò", "cốt dừa", "quế", "hồi"], ["Nấu lòng bò mềm nhừ với nước cốt dừa béo.", "Chấm bánh mì đặc ruột nước sốt đậm đà.", "Món ăn vặt đường phố Sài Gòn quen thuộc."], 620),
        ("Gà Ác Tiềm", ["gà ác", "thuốc bắc", "hạt sen"], ["Hầm gà ác vị thuốc bắc sen nhãn nhục.", "Món ăn bổ dưỡng phục hồi sức khỏe tuyệt vời.", "Nước gà ngọt thanh mùi thảo mộc dịu nhẹ."], 350),
        ("Hủ Tiếu Gõ", ["hủ tiếu", "thịt heo", "hành phi"], ["Hủ tiếu bình dân nấu xương ống thanh trong.", "Thêm thịt thái mỏng hành phi tóp mỡ giòn.", "Tiếng gõ đêm khuya quen thuộc phố phường."], 320),
        ("Cá Lóc Kho Tiêu", ["cá lóc", "tiêu xanh", "mắm"], ["Kho cá lóc mắm đường tiêu xanh cay nồng.", "Đun lửa nhỏ đến khi cá chắc lại keo sốt.", "Ăn cùng cơm trắng dưa leo cực bắt miệng."], 380),
        ("Tôm Rim Mặn", ["tôm", "đường", "tỏi", "nước mắm"], ["Xào tôm cháy tỏi rim mắm đường mặn ngọt.", "Vỏ tôm giòn thịt săn chắc thấm gia vị.", "Món mặn dân dã không thể thiếu bữa cơm."], 350),
        ("Khổ Qua Nhồi Thịt", ["khổ qua", "thịt băm", "mộc nhĩ"], ["Nhồi thịt vào mướp đắng nấu canh nước trong.", "Vị đắng thanh mát giải nhiệt cho cơ thể.", "Nêm hành lá ngò rí dùng nóng với cơm."], 250),
        ("Canh Bí Đỏ Dừa", ["bí đỏ", "tôm khô", "cốt dừa"], ["Nấu bí đỏ chín nhừ tôm khô rưới cốt dừa.", "Vị béo ngậy của dừa quyện cùng bí ngọt bùi.", "Món canh khoái khẩu của trẻ em miền Tây."], 310),
        ("Gà Kho Gừng Nam Bộ", ["thịt gà", "gừng", "nước màu"], ["Kho gà sém cạnh gừng thái chỉ nước màu dừa.", "Thịt gà săn chắc vị ấm nồng từ gừng già.", "Chan nước kho vào cơm trắng cực kỳ hấp dẫn."], 410),
        ("Ốc Bươu Nhồi Thịt", ["ốc bươu", "thịt băm", "sả"], ["Nhồi thịt ốc băm vào vỏ hấp cùng sả thơm.", "Chấm nước mắm gừng sền sệt cay chua ngọt.", "Vị giòn sần sật thịt ốc quyện cùng giò sống."], 380),
        ("Bún Riêu Giò Heo", ["bún", "riêu cua", "giò heo"], ["Ninh giò heo mềm nấu cùng riêu cua đồng.", "Thêm huyết đậu hũ chan nước dùng cà chua.", "Ăn kèm rau muống bào bắp chuối kinh giới."], 580),
        ("Bánh Canh Cua", ["bánh canh", "thịt cua", "trứng cút"], ["Nấu nước dùng sệt gạch cua vàng óng ánh.", "Thêm thịt cua tươi và trứng cút luộc.", "Sợi bánh canh bột lọc dai trong mướt miệng."], 490),
        ("Cá Linh Kho Lạt", ["cá linh", "nước dừa", "xoài"], ["Kho cá linh non nước dừa tươi ăn kèm xoài.", "Vị ngọt thịt cá linh hòa vị chua xoài xanh.", "Món ngon đậm chất sông nước miền Tây Nam."], 330),
        ("Gỏi Ngó Sen", ["ngó sen", "tôm", "thịt ba chỉ"], ["Trộn ngó sen tôm thịt luộc với giấm đường.", "Rắc đậu phộng rang hành phi rau thơm thơm.", "Ăn kèm bánh phồng tôm chiên giòn tan béo."], 270),
        ("Bánh Tét Trà Cuôn", ["gạo nếp", "thịt heo", "lá cẩm"], ["Gói nếp nương nhân thịt mỡ đậu xanh trứng.", "Luộc liên tục trong lu nước suốt 12 tiếng.", "Lớp nếp tím lá cẩm bùi béo đẹp mắt thơm."], 500),
        ("Bánh Gan Nam Bộ", ["trứng gà", "hồi", "đường thốt nốt"], ["Đánh trứng với đường thốt nốt nướng lò nóng.", "Bánh xốp mịn màu nâu đậm như gan heo.", "Món tráng miệng truyền thống Nam Bộ xưa."], 320),
        ("Chè Chuối Thưng", ["chuối sứ", "cốt dừa", "khoai"], ["Nấu chuối nhừ với cốt dừa và khoai bùi.", "Rắc thêm đậu phộng rang giòn khi thưởng thức.", "Vị béo ngậy ngọt lịm xua tan mệt mỏi."], 350),
        ("Lẩu Gà Lá Giang", ["thịt gà", "lá giang", "măng chua"], ["Nấu lẩu gà lá giang chua thanh giải nhiệt.", "Ăn cùng bún tươi rau muống cải xanh bẹ.", "Vị chua đặc trưng lá giang quyện thịt gà."], 420),
        ("Khô Cá Sặc Kho", ["khô cá sặc", "thơm", "ớt"], ["Kho cá khô sặc với thơm và nước màu mắm.", "Nêm đường ớt vị mặn ngọt đậm chất quê hương.", "Món ăn đưa cơm giản dị mộc mạc miền Tây."], 390)
    ]

    # --- MÓN ÂU (50 MÓN) ---
    western = [
        ("Beefsteak Classic", ["thịt bò", "bơ", "rosemary", "khoai tây"], ["Áp chảo thịt bò thăn với bơ tỏi rosemary.", "Chiên khoai tây vàng giòn làm món ăn kèm.", "Nấu sốt tiêu đen rưới lên miếng steak nóng."], 700),
        ("Spaghetti Carbonara", ["mì ý", "bacon", "cheese", "cream"], ["Luộc mì ý vừa chín tới al dente dẻo dai.", "Xào thịt ba rọi xông khói cho giòn cạnh.", "Trộn mì nóng với kem trứng và phô mai bào."], 651),
        ("Pizza Pepperoni", ["đế pizza", "phô mai", "xúc xích", "sốt cà"], ["Phết sốt cà rắc phô mai Mozzarella đều tay.", "Xếp xúc xích Pepperoni lên mặt nướng giòn.", "Nướng lò 200 độ C trong 15 phút là hoàn tất."], 902),
        ("Salad Caesar", ["xà lách", "mayonnaise", "parmesan", "ức gà"], ["Rửa sạch xà lách trộn cùng sốt Caesar phô mai.", "Ức gà nướng vàng thái lát mỏng đặt lên trên.", "Thêm bánh mì giòn croutons rắc phô mai bào."], 353),
        ("Cá Hồi Áp Chảo", ["cá hồi", "măng tây", "chanh", "bơ"], ["Áp chảo phi lê cá hồi da giòn rụm béo thơm.", "Xào nhanh măng tây với bơ tỏi giữ màu xanh.", "Làm sốt bơ chanh chua nhẹ rưới lên cá hồi."], 504),
        ("Lasagna Beef", ["mì lasagna", "thịt bò băm", "sốt cà", "cheese"], ["Nấu sốt bò băm cà chua hành tây đậm đà.", "Xếp lớp mì sốt thịt và phô mai đút lò nướng.", "Nướng đến khi lớp phô mai trên cùng tan chảy."], 805),
        ("Súp Kem Nấm", ["nấm", "cream", "bơ", "hành tây"], ["Xào nấm với bơ tỏi cho dậy mùi thơm nồng.", "Xay nhuyễn hỗn hợp nấm kem tươi nước dùng gà.", "Đun liu riu súp kem nấm nêm muối tiêu trắng."], 256),
        ("Hamburger Classic", ["bánh mì tròn", "thịt bò xay", "cheese", "xà lách"], ["Nặn bò xay viên nướng chín vàng mọng nước.", "Xếp bánh mì thịt bò phô mai xà lách cà chua.", "Thêm sốt mayonnaise và tương cà lên trên đậy bánh."], 728),
        ("Mì Ý Hải Sản", ["mì ý", "tôm", "mực", "rượu vang"], ["Luộc mì ý xào tỏi dầu olive thêm hải sản.", "Thêm rượu vang trắng khử mùi tanh hải sản.", "Trộn mì rắc thêm ngò tây thái nhỏ thơm mát."], 589),
        ("Risotto Mushroom", ["gạo arborio", "nấm", "cheese", "bơ"], ["Xào gạo bơ thêm nước dùng hầm nấm từng chút.", "Nấu gạo chín dẻo mềm mịn quyện vị phô mai.", "Thêm nấm hương xào thơm trộn cùng cơm dẻo."], 550),
        ("Beef Wellington", ["thịt bò", "nấm", "bánh ngàn lớp", "gan ngỗng"], ["Bọc bò thăn lớp nấm băm pate gan ngỗng béo.", "Cuộn chặt vào lớp bánh mỏng nướng vàng rụm.", "Cắt khoanh steak vàng giòn vỏ mềm mọng thịt."], 850),
        ("Súp Hành Tây Pháp", ["hành tây", "bánh mì", "cheese", "bơ"], ["Xào hành tây bơ lửa nhỏ cho nâu caramel ngọt.", "Ninh nước dùng đậm đà thêm lát bánh mì phô mai.", "Đút lò cho phô mai tan chảy trên mặt bát súp."], 300),
        ("Bò Sốt Vang Âu", ["thịt bò", "rượu vang", "khoai tây", "cà rốt"], ["Ướp bò rượu vang đỏ thảo mộc hầm mềm nhừ.", "Cho khoai tây cà rốt ninh cùng nước sốt vang.", "Dùng nóng chấm bánh mì Pháp đặc ruột thơm."], 620),
        ("Salad Nga", ["khoai tây", "cà rốt", "mayonnaise", "giò"], ["Luộc chín rau củ thái hạt lựu trộn mayonnaise.", "Thêm trứng luộc và giò lụa thái nhỏ hòa quyện.", "Để lạnh ngăn mát 1 tiếng trước khi thưởng thức."], 380),
        ("Sườn Cừu Nướng", ["sườn cừu", "rosemary", "tỏi", "khoai"], ["Ướp sườn hương thảo tỏi băm dầu olive thơm.", "Nướng sườn trên vỉ cho chín hồng đào mọng nước.", "Ăn kèm khoai tây nghiền mịn sốt bạc hà xanh."], 750),
        ("Trứng Cuộn Pháp", ["trứng gà", "cheese", "bơ", "hành"], ["Đánh trứng mượt cuộn cùng bơ và phô mai sợi.", "Mặt trứng vàng mịn bên trong phô mai chảy.", "Món ăn sáng tinh tế giàu dinh dưỡng kiểu Âu."], 280),
        ("Cá Ngừ Áp Chảo", ["cá ngừ", "vừng", "chanh", "wasabi"], ["Lăn miếng cá ngừ qua lớp vừng trắng đen dày.", "Áp chảo tái các mặt cá ngừ nhanh trên lửa lớn.", "Thái lát chấm nước tương xì dầu pha wasabi."], 400),
        ("Tôm Cocktail", ["tôm", "sốt cocktail", "xà lách", "chanh"], ["Luộc tôm bóc vỏ bỏ chỉ lưng để lạnh sâu.", "Xếp tôm quanh ly xà lách kèm sốt hồng cocktail.", "Món khai vị mát lạnh sang trọng bữa tiệc Âu."], 200),
        ("Súp Bí Đỏ Âu", ["bí đỏ", "cream", "hành tây", "bơ"], ["Hầm bí đỏ nhừ xay mịn quyện kem tươi béo.", "Xào hành tây bơ cho thơm trộn vào súp nóng.", "Rắc hạt bí rang giòn lên mặt bát súp vàng."], 240),
        ("Mì Ý Sốt Bò Băm", ["mì ý", "thịt bò xay", "cà chua", "cheese"], ["Luộc mì ý dai ngon nấu sốt bolognese bò băm.", "Ninh sốt cà chua thịt bò đậm đà dậy mùi tỏi.", "Chan sốt lên mì rắc thêm phô mai bột thơm."], 600),
        ("Gà Parmigiana", ["ức gà", "cheese", "sốt cà", "bột chiên"], ["Tẩm bột ức gà chiên giòn phủ sốt cà chua.", "Rắc phô mai Mozzarella đút lò cho chảy vàng.", "Vỏ gà giòn rụm quyện phô mai béo ngậy sốt."], 580),
        ("Salad Khoai Tây", ["khoai tây", "mayonnaise", "trứng", "ngò"], ["Luộc khoai tây cắt vuông trộn sốt mayonnaise.", "Thêm trứng luộc thái lát và ngò tây thái vụn.", "Món salad lạnh bùi béo khai vị bữa tối Âu."], 320),
        ("Súp Hải Sản", ["tôm", "mực", "vẹm", "cà chua"], ["Ninh nước hải sản từ xương cá và rau củ lọc.", "Nấu cà chua hành tây thêm tôm mực vẹm tươi.", "Vị súp ngọt thanh mang phong vị biển cả sâu."], 350),
        ("Pizza 4 Phô Mai", ["đế pizza", "mozzarella", "cheddar", "parmesan"], ["Phết dầu olive lên đế bánh nướng sơ một mặt.", "Rắc 4 loại phô mai khác nhau phủ kín mặt bánh.", "Nướng giòn tan thơm lừng mùi phô mai đặc biệt."], 850),
        ("Mì Ý Sốt Ngao", ["mì ý", "ngao", "rượu vang", "tỏi"], ["Luộc mì spaghetti xào ngao tươi với tỏi băm.", "Thêm rượu vang trắng đậy nắp cho ngao há miệng.", "Trộn mì vào chảo ngao rắc tiêu ngò tây thơm."], 450),
        ("Cá Chẽm Áp Chảo", ["cá chẽm", "chanh", "bơ", "khoai tây"], ["Áp chảo phi lê cá chẽm da giòn thịt trắng mềm.", "Làm sốt bơ chanh tỏi rưới lên mặt miếng cá.", "Ăn kèm khoai tây chiên muối tiêu và xà lách."], 480),
        ("Bánh Mì Bruschetta", ["bánh mì", "cà chua", "tỏi", "basil"], ["Nướng lát bánh mì bơ tỏi cho giòn rụm thơm.", "Thái hạt lựu cà chua trộn dầu olive lá quế tây.", "Đặt nhân lên lát bánh mì nướng dùng khai vị."], 180),
        ("Gnocchi Sốt Kem", ["khoai tây", "bột mì", "cheese", "cream"], ["Làm bánh gnocchi khoai tây luộc chín nổi nước.", "Nấu sốt kem phô mai béo ngậy quyện bánh mềm.", "Món mì khoai tây độc đáo của ẩm thực Ý."], 520),
        ("Pizza Rau Củ", ["đế pizza", "ớt chuông", "nấm", "ô liu"], ["Sắp xếp nấm ớt chuông ô liu lên mặt pizza.", "Phủ lớp phô mai trắng nướng lò vàng rụm vỏ.", "Lựa chọn tuyệt vời cho người thích ăn chay Âu."], 700),
        ("Gà Nướng Hương Thảo", ["thịt gà", "rosemary", "chanh", "tỏi"], ["Ướp gà nguyên con hương thảo sả chanh tỏi.", "Nướng lò cho gà chín vàng đều da mọng thịt.", "Vắt thêm chanh lên gà nướng dùng kèm khoai tây."], 610),
        ("Spaghetti Marinara", ["mì ý", "sốt cà", "tôm", "mực"], ["Nấu sốt cà chua hải sản tôm mực tươi đậm đà.", "Luộc mì ý vừa chín tới chan sốt nóng hổi.", "Rắc thêm ngò tây khô và tiêu xay dậy mùi."], 590),
        ("Boeuf Bourguignon", ["thịt bò", "rượu vang", "nấm", "bacon"], ["Hầm bò rượu vang đỏ Pháp nấm mỡ hun khói.", "Ninh thịt nhừ rã thấm sốt vang đậm đà nhất.", "Món bò hầm kinh điển sang trọng của người Pháp."], 750),
        ("Ratatouille Rau Củ", ["cà tím", "bí ngòi", "ớt chuông", "cà chua"], ["Thái lát mỏng rau củ xếp vòng tròn xen kẽ nhau.", "Nướng cùng sốt cà chua dầu olive thảo mộc Âu.", "Món rau củ nướng nổi tiếng vùng Provence Pháp."], 250),
        ("Paella Hải Sản", ["gạo", "tôm", "vẹm", "nghệ", "mực"], ["Xào hải sản tỏi săn thơm nấu gạo nước dùng nghệ.", "Để cạn nước cho cơm cháy sém đáy chảo đặc trưng.", "Món cơm đặc sản nghệ vàng rực rỡ của Tây Ban Nha."], 680),
        ("Fish and Chips", ["cá phi lê", "khoai tây", "bột bia", "bia"], ["Nhúng cá vào bột pha bia rồi chiên vàng giòn.", "Chiên khoai tây miếng dài tẩm muối tiêu kèm cá.", "Ăn kèm sốt tartar chua béo kiểu truyền thống Anh."], 650),
        ("Mì Ý Sốt Kem Nấm", ["mì ý", "nấm", "cream", "cheese"], ["Xào nấm mỡ với bơ tỏi phi cho thơm nồng.", "Cho kem tươi phô mai vào nấu sệt lại béo ngậy.", "Trộn mì spaghetti vào sốt nấm dùng nóng hổi."], 610),
        ("Sườn Bò BBQ", ["sườn bò", "sốt BBQ", "ngô ngọt", "bơ"], ["Ướp sườn bò sốt BBQ đậm đà nướng than hoa.", "Sườn cháy xém cạnh thơm lừng quyện sốt béo.", "Ăn kèm ngô ngọt nướng bơ tỏi và khoai tây."], 820),
        ("Salad Cá Ngừ Âu", ["cá ngừ", "xà lách", "mayonnaise", "bắp"], ["Trộn cá ngừ đóng hộp sốt mayonnaise hành tây bào.", "Bày cá lên lớp rau xà lách tươi thêm bắp hạt.", "Món salad nhanh gọn giàu đạm cho bữa trưa."], 300),
        ("Sandwich Gà Nướng", ["bánh mì lát", "ức gà", "cheese", "mayo"], ["Kẹp ức gà nướng và phô mai lát vào bánh mì.", "Nướng áp chảo cho vỏ bánh giòn rụm phô mai chảy.", "Dùng cho bữa sáng hoặc bữa trưa nhanh tại chỗ."], 450),
        ("Tôm Nướng Bơ Tỏi", ["tôm", "bơ", "tỏi", "ngò tây"], ["Ướp tôm tươi bơ tỏi ngò tây nướng lò 10 phút.", "Vỏ tôm đỏ hồng thịt dai ngọt thấm bơ tỏi thơm.", "Món hải sản nướng hấp dẫn cho bữa tiệc Âu."], 380),
        ("Bò Cuộn Nấm", ["thịt bò lát", "nấm kim châm", "sốt tiêu"], ["Cuộn nấm kim châm vào thịt bò mỏng ướp tiêu.", "Áp chảo bò cuộn nấm cho chín tới thơm lừng.", "Rưới sốt tiêu đen đậm đà lên mặt món ăn."], 420),
        ("Pizza Hải Sản Âu", ["đế pizza", "tôm", "mực", "cheese"], ["Xếp hải sản tôm mực tươi lên đế pizza sốt cà.", "Rắc lớp phô mai dày nướng giòn rụm trong lò.", "Hương vị biển cả quyện phô mai béo ngậy cực ngon."], 880),
        ("Mì Ý Sốt Pesto", ["mì ý", "basil", "hạt thông", "cheese"], ["Xay nhuyễn lá quế tây hạt thông tỏi dầu olive.", "Trộn sốt pesto xanh vào mì ý nóng dẻo thơm.", "Vị thơm nồng nàn thanh mát đặc trưng vùng Ý."], 430),
        ("Cá Hồi Sốt Cam", ["cá hồi", "nước cam", "măng tây", "bơ"], ["Áp chảo cá hồi chín hồng đào da giòn tan.", "Nấu sốt nước cam mật ong bơ rưới lên mặt cá.", "Món cá hồi thanh mát giàu vitamin vị chua ngọt."], 490),
        ("Thịt Cừu Hầm", ["thịt cừu", "khoai tây", "đậu hà lan"], ["Hầm thịt cừu với rượu trắng và thảo mộc khô.", "Cho khoai tây đậu hà lan vào ninh mềm rục.", "Nước sốt cừu đậm đà dùng kèm bánh mì nóng."], 680),
        ("Súp Đậu Hà Lan", ["đậu hà lan", "cream", "bacon"], ["Nấu nhừ đậu hà lan xanh xay mịn cùng kem tươi.", "Thêm kem tươi rắc thịt xông khói chiên giòn lên.", "Màu xanh mát mắt vị bùi béo khai vị hoàn hảo."], 220),
        ("Salad Rau Mầm", ["rau mầm", "trứng", "dầu giấm"], ["Rửa rau mầm trộn dầu giấm tỏi đường thanh mát.", "Thêm trứng luộc lòng đào thái đôi đặt lên mặt.", "Món ăn nhẹ lành mạnh giàu dinh dưỡng cho da."], 150),
        ("Bò Nướng Đá Âu", ["thịt bò thăn", "muối hồng", "tiêu"], ["Đặt miếng thăn bò lên phiến đá nướng nóng rực.", "Lật mặt bò chín đều rắc chút muối hồng tiêu.", "Giữ nguyên độ ngọt mọng nguyên bản của thịt bò."], 550),
        ("Súp Gà Ngô Kem", ["thịt gà", "ngô ngọt", "cream", "bơ"], ["Nấu súp gà ngô băm nhỏ hòa cùng kem béo mịn.", "Thêm kem tươi khuấy đều sánh mượt bát súp nóng.", "Vị ngọt từ ngô béo từ kem tươi tan trong miệng."], 280),
        ("Steak Cá Ngừ", ["cá ngừ", "vừng", "salad"], ["Áp chảo tái cá ngừ tẩm vừng đen trắng đẹp mắt.", "Thái lát mỏng cá ngừ trình bày ra đĩa rộng.", "Ăn kèm salad dầu giấm chua ngọt kích thích vị giác."], 410)
    ]

    all_recipes = []
    # Ghép 4 vùng miền lại thành danh sách 200 món
    for items, region in [(north, "Miền Bắc"), (central, "Miền Trung"), (south, "Miền Nam"), (western, "Món Âu")]:
        for dish in items:
            all_recipes.append({
                "name": dish[0],
                "region": region,
                "ingredients": dish[1],
                "steps": dish[2],
                "calories": dish[3]
            })

    with open('recipes.json', 'w', encoding='utf-8') as f:
        json.dump(all_recipes, f, ensure_ascii=False, indent=4)
    
    print(f"✅ Thành công! Đã tạo 200 món ăn CHI TIẾT TỪNG BƯỚC cho Quân.")

if __name__ == "__main__":
    generate_final_database()